build:
    environment:
        php:
            version: 5.6.16

    cache:
        directories:
            - ~/cphalcon

    dependencies:
        override:
            - composer install --prefer-source --no-interaction
        after: 
            - vendor/bin/install-phalcon.sh

filter:
    paths:
        - 'src/*'
     
checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    php_code_sniffer:
        config:
            standard: PSR2